// src/components/Navbar/navbar.jsx
import React, {Component} from 'react'
import { menuItems } from './menuItems'
import { Link } from 'react-router-dom'
import ContactModal from '../ContactModal/contact_modal';

import './navbar.min.css'


class Navbar extends Component {
    // Clicked used to change navbar icon, margin used to change navbar style to avoid overlapping
    state = { clicked: false, margin: 80}
    modal_state = {clicked: false}

    handleClick = () => {
        this.setState({clicked:!this.state.clicked})
        let isClicked = this.state.clicked;
        if (isClicked === true){
            this.setState({margin: 80})
        }
        else{
            this.setState({margin: 300})
        }
    }
    handleModal = () => {
        this.setState({clicked:!this.modal_state.clicked})
        let isClicked = this.state.clicked;
        if (isClicked === true){
            this.setState({margin: 80})
        }
        else{
            this.setState({margin: 300})
        }
    }

    render(){
        const css = `
        @media screen and (max-width: 960px) {
            .c-navbar-items {
                margin-bottom: ${this.state.margin}px;
                transition: all 0.5s ease-in-out;
            }

            .c-nav-menu {
                height:200px;
            }

            #contact_modal {
                padding-bottom: 0;
                padding-top: 29.5px;
            }
            .c-navbar-logo {
                padding-top: 4px;
            }
        }
        `
        return(
                <nav className="c-navbar-items">
                    <Link className="c-navbar-logo" to='/home'>
                        <h1>
                        Alvaro
                        <i className='fab fa-react'></i>
                        </h1>
                    </Link>
                    <div className="c-menu-icon" onClick={this.handleClick}>
                        <i className={this.state.clicked ? 'fas fa-times' : 'fas fa-bars'}></i>
                    </div>
                    <ul className={this.state.clicked ? 'c-nav-menu active' : 'c-nav-menu'}>
                        {menuItems.map((item, index) => {
                            return (
                                <li key={index}>
                                        <Link className={item.cName} to={item.url}>
                                            {item.title}
                                        </Link>
                                </li>
                            )
                            })}
                        <style>
                            {css}
                        </style>
                    </ul>
                    <ContactModal/>
                </nav>
        )
    }
}

export default Navbar

// src/components/Navbar/Navbar.vue
<script setup>
import { ref, computed } from 'vue'
import { menuItems } from './menuItems'
import ContactModal from '../ContactModal/ContactModal.vue'
import './navbar.min.css'

const clicked = ref(false)
const margin = ref(80)

function handleClick() {
  clicked.value = !clicked.value
  margin.value = clicked.value ? 300 : 80
}

const mobileCSS = computed(() => `
  @media screen and (max-width: 960px) {
    .c-navbar-items { margin-bottom: ${margin.value}px; transition: all 0.5s ease-in-out; }
    .c-nav-menu { height: 200px; }
    #contact_modal { padding-bottom: 0; padding-top: 29.5px; }
    .c-navbar-logo { padding-top: 4px; }
  }
`)
</script>

<template>
  <nav class="c-navbar-items">
    <RouterLink class="c-navbar-logo" to="/home">
      <h1>Alvaro<i class="fab fa-vuejs"></i></h1>
    </RouterLink>
    <div class="c-menu-icon" @click="handleClick">
      <i :class="clicked ? 'fas fa-times' : 'fas fa-bars'"></i>
    </div>
    <ul :class="clicked ? 'c-nav-menu active' : 'c-nav-menu'">
      <li v-for="(item, index) in menuItems" :key="index">
        <RouterLink :class="item.cName" :to="item.url">{{ item.title }}</RouterLink>
      </li>
      <component is="style">{{ mobileCSS }}</component>
    </ul>
    <ContactModal />
  </nav>
</template>
