// src/components/ProgressBar/ProgressBar.vue
<script setup>
import './progressbar.min.css'

const props = defineProps({
  progress: { type: String, required: true },
  background: { type: String, required: true },
  delay: { type: String, required: true },
})

const fillClass = `progressbar-fill-${props.progress}`
const keyframeName = `fill-${props.progress}`
const css = `
.${fillClass} {
  width: ${props.progress}%;
  height: 100%;
  background: ${props.background};
  border-radius: 4px;
  animation: ${keyframeName} ${1 + parseInt(props.delay)}s forwards;
}
@keyframes ${keyframeName} {
  from { width: 0%; }
  to   { width: ${props.progress}%; }
}
`
</script>

<template>
  <div class="progressbar">
    <div :class="fillClass">
      <span class="progress-text">{{ progress }}%</span>
    </div>
    <component is="style">{{ css }}</component>
  </div>
</template>

// src/components/ProgressBar/progressbar.jsx
import "./progressbar.min.css"


function ProgressBar(props) {
    // To set the progressbar text dynamically
    let percentage = props.progress;
    let background = props.background;
    let animation_delay = props.delay
    // Create necessary css to create the fill of the progressbar
    let fill_classname = `progressbar-fill-${percentage}`
    const css = `
    .${fill_classname} {
        width: ${percentage}%;
        height: 100%;
        background: ${background};
        border-radius: 4px;
        animation: transition ${1 + parseInt(animation_delay)}s;
    }

    @keyframes transition {
        from {
            width: 0%;
        }
        to {
            width: ${percentage}
        }
    }
    `
    return(
        <div className="progressbar">
            <div className={fill_classname}>
                <span className="progress-text">{percentage}%</span>
            </div>
            <style>
                {css}
            </style>
        </div>
    )
}

export default ProgressBar
